### ISSUE TITLE
warn] o.w.RequireJS - Could not read WebJar RequireJS config for: requirejs 2.1.14

### ISSUE THREAD

**Issue by gaojc** [webjars/requirejs#15]
jcgao@Aspire:~/ideaprojects/paws-master$ sbt
[info] Loading project definition from /home/jcgao/ideaprojects/paws-master/project
[info] Set current project to paws (in build file:/home/jcgao/ideaprojects/paws-master/)
[paws] $ run
[info] Updating {file:/home/jcgao/ideaprojects/paws-master/}paws...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.

--- (Running the application from SBT, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[info] application - [securesocial] loaded templates plugin: plugins.users.CustomTemplatesPlugin
[info] play - Starting application default Akka system.
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[debug] application - [securesocial] calling deleteExpiredTokens()
[info] application - [securesocial] loaded user service: class plugins.users.sorm.SormUserServicePlugin
[info] application - [securesocial] loaded password hasher bcrypt
[info] application - [securesocial] loaded identity provider: userpass
[info] play - Application started (Dev)
[warn] o.w.RequireJS - Could not read WebJar RequireJS config for: requirejs 2.1.14
Please file a bug at: http://github.com/webjars/requirejs/issues/new

**Comment by jamesward** [comment]
This was fixed via #11 so please use a newer version.
